server: 
  port: dev
spring:
  http: 
    multipart:
      max-file-size: 5000Mb
      max-request-size: 2000Mb
  application:
    name: xm-fd-client-server   
  datasource:
    url: jdbc:mysql://106.14.150.60:3306/testmr?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: testmr
    password: testmr123
    #url: jdbc:mysql://106.14.150.60:3306/xmdb?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=true
    #username: root
    #password: A123456
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 20
      min-idle: 3
      max-idle: 10
      max-total: -1
      
  thymeleaf:
    cache: false
    encoding: UTF-8
logging:
  file: xm-fd-server.log
  level: 
    root: warn    
eureka: 
  client: 
      serviceUrl: 
        #defaultZone: http://eureka:eurekawangpudata@video.meirendaifu.com:8000/eureka,http://eureka:eurekawangpudata@meirendaifu.com:7000/eureka/
        defaultZone: http://eureka:eurekawangpudata@test.meirendaifu.com:8000/eureka
        #defaultZone: http://admin:tulubi123@peer1:8761/eureka,http://admin:tulubi123@peer2:8762/eureka
eureka.instance.hostname: xm-fd-client-server-host
eureka.instance.prefer-ip-address: true
eureka.instance.instance-id: ${eureka.instance.ip-address}:${server.port}
xm-activity-web: 
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule                                    
logging.level.org.springframework.web: DEBUG
logging.level.com.wangpudata.xm.feidao: DEBUG
mybatis:
     mapperLocations:
           classpath:com/wangpudata/xm/feidao/*/dao/*-mapper.xml


