spring: 
  datasource:
    url: jdbc:mysql://106.14.150.60:3306/testmr?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: testmr
    password: testmr123
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 20
      min-idle: 3
      max-idle: 10
      max-total: -1
file_root: uploadFiles
name: mademademmmmmm

